### ISSUE TITLE
how do you download it?

### ISSUE THREAD

**Issue by Parkerdaboss216** [battlecatsultimate/BCU_Android#1]

**Comment by MandarinSmell** [comment]
If you are in BCU discord server, read installation-guide. Or tell me if you aren't in server, I will give you invitation link. I will close this issue because it's really basic thing. You can google it if you don't know how to download files from github too

**Comment by Parkerdaboss216** [comment]
k, im not in the server so i do need a link.

**Comment by MandarinSmell** [comment]
@Parkerdaboss216 Here

https://discord.gg/zvqamBW

**Comment by Parkerdaboss216** [comment]
hlap, its not letting me in XD
