### ISSUE TITLE
Can't Download the App

### ISSUE THREAD

**Issue by KVN10790** [battlecatsultimate/BCU_Android#10]
I Know this is in Work but i can not Download BCU for Android i can't find the Download Button anywhere (sorry im new on github) do u add it later or already have added it?

**Comment by MandarinSmell** [comment]
Go to [this link](https://github.com/battlecatsultimate/bcu-assets/tree/master/apk). You will see apk list. Select the latest version (For now, it's 0.18.7). If you go in there, You will see `...` button next to `Code` and `Blame` button. Then `Download` button will appear

Or, you can just simply tap `View raw`, but in the case when this way doesn't work, follow the way above. Update itself can be done by app. It will catch new version as long as your device is connected to the internet

**Comment by KVN10790** [comment]
Ah see it thx

Mandarin Smell ***@***.***> schrieb am Sa., 14. Okt. 2023,
11:33:

**Comment by KVN10790** [comment]
Btw can u add the pc features crestor of level and cats to apk? Like edit
cat stats

Mandarin Smell ***@***.***> schrieb am Sa., 14. Okt. 2023,
11:33:

**Comment by MandarinSmell** [comment]
No, custom contents won't be implemented with high chance since I lost willing to maintain that part. Now issue is resolved, I will close the issue

**Comment by KVN10790** [comment]
Oh ok but do you still work on bcu? I amke a custom anti angel reward quest

Mandarin Smell ***@***.***> schrieb am Mo., 16. Okt. 2023,
02:26:
