### ISSUE TITLE
How to download???

### ISSUE THREAD

**Issue by Cool-cat10** [battlecatsultimate/BCU_Android#12]
Can't download

**Comment by MandarinSmell** [comment]
1. Go to [this link](https://github.com/battlecatsultimate/bcu-assets/blob/master/apk/BCU_Android_0.18.12.apk), and click `...`
2. Click `Download`
3. Apk will be downloaded into your device, access apk file via file browser, and install it

<div align="center">

| <img width=50% height=50% src="https://cdn.discordapp.com/attachments/642008685199228946/1201351334671171774/Screenshot_20240129_112107_Samsung_Internet.jpg?ex=65c9809e&is=65b70b9e&hm=8146de9ec11c7ab75f36164840110b517815aba8cad203ae7e84eb4f311af29d&"/> |
| :----: |
| Example |

</div>

**Comment by MandarinSmell** [comment]
Closing issue due to inactiveness
