### ISSUE TITLE
How to find the temp or pack file that contains my BCU Pack on an M1 Mac?

### ISSUE THREAD

**Issue by MrbeegamerGitHub** [battlecatsultimate/BCU_Android#7]
Sorry but I need help another time I don't really know terminal so can you help me?

**Comment by MandarinSmell** [comment]
You can try to go to music managing page.

1. In main menu, click custom pack (Go to custom pack managing page)
2. Then select one of your pack, and click musics
3. Click show button

Then it will open folder where your pack's music folder is. Get out of music folder a bit until you see a folder called `workspace`. There will be another folders such as `assets`, `user`, etc. Go to `exports` folder and that's the folder where your exported packs exist 

We have fixed this relative path problem, so in BCU folder, move contents of it into your Desktop folder (Create new folder in Desktop), then download BCU-Initializer.jar file again, put it into your BCU folder, and open it

Also this is BCU Android repo, not BCU PC. Ask for help about BCU PC in there next time
